services:
  trainer:
    image: pytorch/pytorch:2.6.0-cuda12.4-cudnn9-devel
    container_name: ml-trainer-dev
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CODE_DIR=/app
      - DATA_DIR=/mnt/data
      - OUTPUT_DIR=/mnt/outputs
    volumes:
      - ./requirements.txt:/tmp/requirements.txt
      - ./code:/app
      - /mnt/external_drive/ml-data:/mnt/data
      - ./outputs:/mnt/outputs
    working_dir: /app
    command: >
      bash -c "
        pip install -r /tmp/requirements.txt &&
        exec bash"
    stdin_open: true
    tty: true
    runtime: nvidia